server.port: 8081

spring.jpa.properties.hibernate.connection.charSet: UTF-8
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.url: jdbc:mysql://localhost:3306/quicky?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
spring.datasource.username: root
spring.datasource.password: root